//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obadaella_Vidyalaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Register
    {
        public int EMPNO { get; set; }
        public string EMPCODE { get; set; }
        public string EMPNAME { get; set; }
        public string EMPDESIGNATION { get; set; }
        public string EMPNIC { get; set; }
        public string EMPADDRESS { get; set; }
        public string EMPGENDER { get; set; }
        public string EMPDOB { get; set; }
        public string EMPCONTACT { get; set; }
        public string EMPEMAIL { get; set; }
        public System.DateTime EMPDATE { get; set; }
    }
}
