//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obadaella_Vidyalaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Attendance
    {
        public int ATTENDID { get; set; }
        public string EMPCODE { get; set; }
        public string EMPNAME { get; set; }
        public string DESIGNATION { get; set; }
        public string STATUS { get; set; }
        public string DATE { get; set; }
    }
}
