//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obadaella_Vidyalaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalaryDetail
    {
        public int EmpSalNo { get; set; }
        public string EmpPayID { get; set; }
        public string EmployeeID { get; set; }
        public string Bank { get; set; }
        public string Branch { get; set; }
        public string Account { get; set; }
        public Nullable<int> Basic { get; set; }
        public Nullable<int> Allowances { get; set; }
        public Nullable<int> Loan { get; set; }
        public Nullable<int> TotalSalary { get; set; }
    }
}
