//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obadaella_Vidyalaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Tasks
    {
        public int TASKID { get; set; }
        public string EMPCODE { get; set; }
        public string EMPLOYEENAME { get; set; }
        public string TASKNAME { get; set; }
        public System.DateTime TASKDATE { get; set; }
    }
}
