//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obadaella_Vidyalaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hall
    {
        public int id { get; set; }
        public string Hall_id { get; set; }
        public string Hall_name { get; set; }
        public string Class { get; set; }
    }
}
