//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obadaella_Vidyalaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPayment
    {
        public int StudentPayNo { get; set; }
        public string StudentID { get; set; }
        public string StudentName { get; set; }
        public string StudentGrade { get; set; }
        public string ExamFee { get; set; }
        public string FacilityFee { get; set; }
        public string TotalFee { get; set; }
    }
}
