//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obadaella_Vidyalaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Table
    {
        public int USERNO { get; set; }
        public string EMPLOYEEID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
    }
}
